### ISSUE TITLE
MySQL-python can't be installed

### ISSUE THREAD

**Issue by Moini** [lrivallain/openshift-django1.7-py3#1]
Hi Irivallain,

thank you for the instructions and the 'template'! 
It seems that openshift has made some changes. MySQL does not work out of the box.

If you try to use the django install directly as you created it, it will give an error about a missing module (MySQL-python) and will not start up.

If you try to pip install that module, it will also give you an error:
from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser

I found a solution to this at stackoverflow:
http://stackoverflow.com/questions/24584244/installing-mysql-python-module-on-openshift
(adds PyMySQL 0.6.3 (latest available version at openshift) to requirements.txt, and makes django use it instead of mysql-python via settings.py) and it seems to work well.

Could you add these small changes to your 'template' or to the README ?

 Moini

EDIT: This is the solution by Sagan at stackoverflow

**Comment by jTiKey** [comment]
try:
      import pymysql
      pymysql.install_as_MySQLdb()
except ImportError:
      pass

needs to be added to the settings as well.

**Comment by Moini** [comment]
That's what I meant by "makes django use it instead of mysql-python via settings.py" ;)

**Comment by Moini** [comment]
And another thing I just discovered: maybe add something in for ALLOWED_HOSTS in the settings.py file? Not sure if this really makes a difference at openshift...

I did this (again, upon advice from stackoverflow etc.):

from socket import gethostname

if DEBUG:
     ALLOWED_HOSTS = []
else:
     ALLOWED_HOSTS = [ gethostname(), # For internal OpenShift load balancer security purposes.
                      os.environ['OPENSHIFT_APP_DNS'], # Dynamically map to the OpenShift gear name.
                      os.environ['OPENSHIFT_GEAR_DNS'],
]

**Comment by lrivallain** [comment]
Thanks @Moini & @jTiKey !

I've just push the fix for PyMySQL. (& sorry for the time it tooks me to answer)

@Moini : Can you split issue for the ALLOWED_HOSTS suggestion ?

**Comment by Moini** [comment]
Yep. Thanks!
