### ISSUE TITLE
Restrict allowed_hosts in settings.py (from #1 split)

### ISSUE THREAD

**Issue by lrivallain** [lrivallain/openshift-django1.7-py3#2]
Split issue #1 from @Moini 

"And another thing I just discovered: maybe add something in for ALLOWED_HOSTS in the settings.py file? Not sure if this really makes a difference at openshift...

I did this (again, upon advice from stackoverflow etc.):

```
from socket import gethostname
if DEBUG:
    ALLOWED_HOSTS = []
else:
    ALLOWED_HOSTS = [ gethostname(), # For internal OpenShift load balancer security purposes.
    os.environ['OPENSHIFT_APP_DNS'], # Dynamically map to the OpenShift gear name.
    os.environ['OPENSHIFT_GEAR_DNS'],
]
```

"

**Comment by lrivallain** [comment]
Fixed according to the suggestion. Thks.

**Comment by Moini** [comment]
Oh - thanks :)
